// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  serverUrl: 'http://dalfoodbank-env.eba-khbmxtba.us-east-1.elasticbeanstalk.com/api/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  firebase: {
    apiKey: 'AIzaSyCgdoKYC9dCPnnPifjJXwIGdNZ4Ny5XcHU',
    authDomain: 'dalfoodbank.firebaseapp.com',
    databaseURL: 'https://dalfoodbank.firebaseio.com',
    projectId: 'dalfoodbank',
    storageBucket: 'dalfoodbank.appspot.com',
    messagingSenderId: '739396724961',
    appId: '1:739396724961:web:df489daa719c0d8e99efa0',
  },
};
